name: Post Scheduled Workflow

on:
  # push:
  schedule:
    - cron: '0 10 * * *' # 19:00 at Japan (UTC 10:00)

jobs:
  run-typescript:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build TypeScript
      run: npm run build

    - name: Run TypeScript Script
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_BLOG_COLLECTION: ${{ secrets.FIREBASE_BLOG_COLLECTION }}
        TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
        TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      run: node dist/announcement.js
